<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="DataEmerg.aspx.cs" Inherits="DataEmerg" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <!---table---->
    <div class="container"><br /><br />
        <div class="panel panel-default" style="overflow:auto;">
              <!-- Default panel contents -->
            <div class="panel-heading">All Data<br />
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
                     AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
                     DataKeyNames="EId" DataSourceID="SqlDataSource2" CellPadding="4" ForeColor="#333333" GridLines="None">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                    <Columns>
                        <asp:BoundField DataField="EId" HeaderText="EId" InsertVisible="False" ReadOnly="True" SortExpression="EId" />
                        
                        <asp:BoundField DataField="EName" HeaderText="EName" SortExpression="EName" />
                        <asp:BoundField DataField="ELocation" HeaderText="ELocation" SortExpression="ELocation" />
                        <asp:BoundField DataField="EContact" HeaderText="EContact" SortExpression="EContact" />
                        
                    </Columns>
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:UserConnectionString1 %>" DeleteCommand="DELETE FROM [TblEmg] WHERE [EId] = @EId" InsertCommand="INSERT INTO [TblEmg] ([EName], [ELocation], [EContact]) VALUES (@EName, @ELocation, @EContact)" SelectCommand="SELECT * FROM [TblEmg]" UpdateCommand="UPDATE [TblEmg] SET [EName] = @EName, [ELocation] = @ELocation, [EContact] = @EContact WHERE [EId] = @EId">
                    <DeleteParameters>
                        <asp:Parameter Name="EId" Type="Int64" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="EName" Type="String" />
                <asp:Parameter Name="ELocation" Type="String" />
                <asp:Parameter Name="EConatact" Type="String" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="EName" Type="String" />
                <asp:Parameter Name="ELocation" Type="String" />
                <asp:Parameter Name="EConatact" Type="String" />
                        <asp:Parameter Name="EId" Type="Int64" />
                    </UpdateParameters>
                </asp:SqlDataSource>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server"
                    ConnectionString="<%$ ConnectionStrings:UserConnectionString1 %>"
                     SelectCommand="SELECT * FROM [TblEmg]" 
                    UpdateCommand="UPDATE [TblEmg] SET [EName]=@EName,[ELocation]=@ELocation,[EContact]=@EContact WHERE [EId]=@EId" 
                    DeleteCommand="DELETE from [TblEmg] where [EId]=@EId">
                    <UpdateParameters>
                
                <asp:Parameter Name="EName" Type="String" />
                <asp:Parameter Name="ELocation" Type="String" />
                <asp:Parameter Name="EConatact" Type="String" />
                
                <asp:Parameter Name="EId" Type="Int64" />
            </UpdateParameters>
                </asp:SqlDataSource>
              </div>
          </div>
              <!-- Table -->
             
                        
                    
        </div>
        <!---table end--->
</asp:Content>

