<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="resData.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

      <!---table---->
    <p style="text-align:center; vertical-align:central; padding:10px;">
    <div class="container"><br /><br />
        <div class="panel panel-default" style="overflow:auto;">
              <!-- Default panel contents -->
            <div class="panel-heading">All Data<br />
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
                     AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
                     DataKeyNames="DID" DataSourceID="SqlDataSource2" CellPadding="4" ForeColor="#333333" GridLines="None">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                    <Columns>
                        <asp:BoundField DataField="DID" HeaderText="DID" InsertVisible="False" ReadOnly="True" SortExpression="DID" />
                        <asp:BoundField DataField="type" HeaderText="type" SortExpression="type" />
                        <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                        <asp:BoundField DataField="location" HeaderText="location" SortExpression="location" />
                        <asp:BoundField DataField="contact" HeaderText="contact" SortExpression="contact" />
                        <asp:BoundField DataField="description" HeaderText="description" SortExpression="description" />
                    </Columns>
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:UserConnectionString1 %>" DeleteCommand="DELETE FROM imageT WHERE [DID]=@DID;DELETE FROM [dataTable] WHERE [DID] = @DID" InsertCommand="INSERT INTO [dataTable] ([type], [name], [location], [contact], [description]) VALUES (@type, @name, @location, @contact, @description)" SelectCommand="SELECT * FROM [dataTable]" UpdateCommand="UPDATE [dataTable] SET [type] = @type, [name] = @name, [location] = @location, [contact] = @contact, [description] = @description WHERE [DID] = @DID">
                    <DeleteParameters>
                        <asp:Parameter Name="DID" Type="Int64" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="type" Type="String" />
                        <asp:Parameter Name="name" Type="String" />
                        <asp:Parameter Name="location" Type="String" />
                        <asp:Parameter Name="contact" Type="String" />
                        <asp:Parameter Name="description" Type="String" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="type" Type="String" />
                        <asp:Parameter Name="name" Type="String" />
                        <asp:Parameter Name="location" Type="String" />
                        <asp:Parameter Name="contact" Type="String" />
                        <asp:Parameter Name="description" Type="String" />
                        <asp:Parameter Name="DID" Type="Int64" />
                    </UpdateParameters>
                </asp:SqlDataSource>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server"
                    ConnectionString="<%$ ConnectionStrings:UserConnectionString1 %>"
                     SelectCommand="SELECT * FROM [dataTable]" 
                    UpdateCommand="UPDATE [dataTable] SET [type]=@type,[name]=@name,[location]=@location,[contact]=@contact,[description]=@description WHERE [DID]=@DID" 
                    DeleteCommand="DELETE FROM imageT WHERE [DID]=@DID;DELETE FROM [dataTable] WHERE [DID] = @DID">
                    <UpdateParameters>
                <asp:Parameter Name="type" type="String"/>
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="location" Type="String" />
                <asp:Parameter Name="conatact" Type="String" />
                <asp:Parameter Name="description"  Type="String"/>
                <asp:Parameter Name="DID" Type="Int64" />
            </UpdateParameters>
                </asp:SqlDataSource>
              </div>
          </div>
              <!-- Table -->
             
                        
                    
        </div>
        <!---table end--->
        </p>

</asp:Content>

